import = ["/home/jager/.config/alacritty/themes/tokyonight_moon.toml"]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "MesloLGM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGM Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/bash"

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.5
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 22

[window.padding]
x = 4
y = 4
